theme: jekyll-theme-minima
logo: portrait.png
google_analytics: UA-9578462-2
title: Golnoosh Farnadi
description: Assistant Professor at McGill University, Adjunct Professor at University of Montr√©al, Core Academic Member at MILA, Canada CIFAR AI (CCAI) Chair holder


