theme: pages-themes/cayman@v0.2.0
plugins: - jekyll-remote-theme
logo: portrait.png
google_analytics: UA-9578462-2
title: Golnoosh Farnadi
description: Assistant Professor at HEC Montréal, Adjunct Professor at University of Montréal, Core Academic Member at MILA, Canada CIFAR AI (CCAI) Chair holder


